### ISSUE TITLE
Run time Error

### ISSUE THREAD

**Issue by Lord-Curdin** [SirRade/JNF_NEAT#23]
Not reproducible Runtime error  Stackoverflow
function: NeuralNetwork::CategorizeNeuronBranchIntoLayers

**Comment by janhohenheim** [comment]
Was perhaps fixed by b83cbde8eba287983a7eb0fd5273ddfed38d4a6f

**Comment by janhohenheim** [comment]
It seems the `isRecursive` flag doesn't get set right sometimes

**Comment by Lord-Curdin** [comment]
Is reproducible look-up issue #28

**Comment by janhohenheim** [comment]
Moved to #28
