### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Lord-Curdin** [SirRade/JNF_NEAT#28]
**Error** Runtime [Stackoverflow]
**function** NeuralNetwork::CategorizeNeuronBranchIntoLayers(Neuron& currNode)

![errorexemple](https://cloud.githubusercontent.com/assets/16896522/16037692/fdb4a332-3221-11e6-9633-d28ac017b77d.JPG)
![errorexemple-1](https://cloud.githubusercontent.com/assets/16896522/16037690/fa31e5c6-3221-11e6-99ad-aa0332c1d29c.JPG)
![errorexemple-2](https://cloud.githubusercontent.com/assets/16896522/16037691/fcd4cd7a-3221-11e6-8509-d5a3b4d25af0.JPG)

**Comment by janhohenheim** [comment]
@Lord-Curdin Could you post a screenshot of the genome involved?

**Comment by janhohenheim** [comment]
![image](https://cloud.githubusercontent.com/assets/9047632/16062125/829c49be-3291-11e6-943c-410ae5fbc621.png)
