### ISSUE TITLE
The produced Json for genomes has one depth too much:

### ISSUE THREAD

**Issue by Mafii** [SirRade/JNF_NEAT#34]
Here is what the genomes in json look like:

`,"genome":{"genome":[{"historicalMarking":0,"from":0,"to":3,"weight":0.252425....`

But, it should be 

`,"genome": [{"historicalMarking":0,"from":0,"to":3,"weight":0.252425....`

Why?

Because the json representing the neurons is:

 `{"neurons":[{"layer":0,"lastActionPotential":1.000000}`

**Comment by SirRade** [comment]
The correct way is actually `,"genome": {[{"historicalMarking":0,"from":0,"to":3,"weight":0.252425....}]}`
