### ISSUE TITLE
Parsing with `stoul` is not portable

### ISSUE THREAD

**Issue by janhohenheim** [SirRade/JNF_NEAT#59]
std::size_t is [not guaranteed](http://en.cppreference.com/w/cpp/types/size_t) to be an unsigned long.
Code like [this](https://github.com/SirRade/Hippocrates/blob/development/Core/Sources/Implementations/training_parameters.cpp#L47) will fail on some architectures.  

[Possible fix](http://stackoverflow.com/questions/34043894/convert-string-to-size-t)

**Comment by janhohenheim** [comment]
This breaks sane windows builds and is unsafe. Possible solutions: 
- use `sscanf_s` on windows instead with some precompiler hacking 
- `#define _CRT_SECURE_NO_WARNINGS` and `#undef` it again if it wasn't defined before
- switch to another method

![image](https://cloud.githubusercontent.com/assets/9047632/20186075/cec244d6-a76e-11e6-9625-11094ea94b73.png)

**Comment by SirRade** [comment]
![image](https://cloud.githubusercontent.com/assets/9047632/20186075/cec244d6-a76e-11e6-9625-11094ea94b73.png)

**Comment by jeremystucki** [comment]
Closed with #64
